Fix Error: Function lookup() did not find a value for the name 'tftp::root'
https://github.com/theforeman/puppet-foreman_proxy/commit/f849d1284d3ee0a41eae4becc8b1a561b668c93c
This change is 'problematic' for us as we don't use tftp (or dns, dhcp) so we don't have the tftp module installed.
It does cause the following error in our catalog compilation

Error: Function lookup() did not find a value for the name 'tftp::root' 

This 'naive' change seems to fix that issue.